import "@radix-ui/themes/styles.css";
import "./theme-config.css";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "./components/NavBar";
import { Theme, ThemePanel } from "@radix-ui/themes";
import Providers from "./providers";
import { getServerSession } from "next-auth";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en" className={inter.variable}>
      <body className={inter.className}>
        <Providers>
          <Theme appearance="light" accentColor="purple">
            <NavBar session={session} />
            <main className="p-5">{children}</main>
          </Theme>
        </Providers>
      </body>
    </html>
  );
}
